In [102]:
#import mysql.connector
from sqlalchemy import create_engine
import pymysql
import numpy as np
import pandas as pd

In [103]:
#pip install openpyxl

In [104]:
#cnx = sqlalchemy.create_engine('mysql+pymysql://root:chilote64@localhost/analitica2')
cnx = create_engine('mysql+pymysql://root:chilote64@localhost/analitica2')

In [105]:
qry="select	clientcode,hiercode,sum(nc) as nc from 	rp_client_preference_hst group by clientcode,hiercode"
df_input=pd.DataFrame(cnx.execute(qry).fetchall())
df_input.columns=['clientcode','hiercode','nc']

In [106]:
df_input.columns=['clientcode','hiercode','nc']

In [107]:
# entire dataframe
df_input

clientcode hiercode nc
0               10  S523920  1
1               10  S524478  1
2          1000000  S527972  1
3          1000000  S527224  1
4          1000000  S522143  1
...            ...      ... ..
4935154   99999999  S528290  1
4935155   99999999  S500668  3
4935156   99999999  S527079  2
4935157   99999999  S529192  1
4935158   99999999  S530935  1

[4935159 rows x 3 columns]

In [108]:
# client list
qry="select distinct clientcode from rp_client_preference_hst"
client_lst=cnx.execute(qry).fetchall()
lst_client =[ lt[0] for lt in pd.DataFrame.from_dict(client_lst).values.tolist()]
lst_client

['10',
 '1000000',
 '10000071',
 '10000083',
 '10000089',
 '10000101',
 '10000125',
 '10000152',
 '10000199',
 '10000202',
 '10000213',
 '10000227',
 '10000253',
 '10000302',
 '10000305',
 '10000414',
 '10000422',
 '10000441',
 '10000458',
 '10000479',
 '10000660',
 '10000786',
 '10000791',
 '10000794',
 '10000799',
 '10000813',
 '10000832',
 '10000927',
 '10000962',
 '10000992',
 '10001048',
 '10001113',
 '10001196',
 '10001269',
 '10001337',
 '10001364',
 '10001385',
 '10001496',
 '10001497',
 '10001631',
 '10001666',
 '10001684',
 '10001724',
 '10001782',
 '10001811',
 '10001927',
 '10001938',
 '10001943',
 '10002090',
 '10002137',
 '10002180',
 '10002208',
 '10002226',
 '10002270',
 '10002293',
 '10002296',
 '10002346',
 '10002359',
 '10002393',
 '10002396',
 '10002458',
 '10002473',
 '10002596',
 '10002598',
 '10002629',
 '10002652',
 '10002745',
 '10002800',
 '10002802',
 '10002804',
 '10002825',
 '10002841',
 '10002860',
 '10002880',
 '10002899',
 '10002904',
 '10002925',
 '1000

In [109]:
list_client_array=np.array(lst_client).reshape((-1,1))

In [110]:
list_client_array

array([['10'],
       ['1000000'],
       ['10000071'],
       ...,
       ['9999960'],
       ['99999992'],
       ['99999999']], dtype='<U8')

In [111]:
print(len(list_client_array))

1022972


In [112]:
# Number of clients to choose randomly
n=20000

In [113]:
# randomly choosing the clients' indexes 
random_array=np.random.choice(len(lst_client),n)

In [114]:
random_array

array([370431, 939380, 863819, ..., 283378, 349133, 136516])

In [115]:
random_array.shape

(20000,)

In [116]:
# convering the index array to a list
mask=random_array.tolist()
mask

[370431,
 939380,
 863819,
 582621,
 1017579,
 660952,
 944701,
 578113,
 442610,
 615051,
 681390,
 678106,
 359680,
 469901,
 743214,
 767947,
 864121,
 493166,
 512487,
 297955,
 181101,
 159264,
 682140,
 906493,
 161773,
 38077,
 13005,
 981253,
 607779,
 117398,
 523045,
 879524,
 292334,
 24062,
 532915,
 811171,
 645122,
 744170,
 582412,
 542683,
 765870,
 622720,
 93402,
 568275,
 9002,
 899759,
 105121,
 623580,
 508036,
 537203,
 499028,
 850227,
 161323,
 962449,
 709861,
 863360,
 883384,
 969604,
 31143,
 582600,
 959339,
 291579,
 144970,
 350859,
 904494,
 384858,
 540600,
 5346,
 514064,
 181226,
 741179,
 776321,
 85545,
 372400,
 223554,
 49819,
 892112,
 904521,
 114948,
 468789,
 701448,
 212804,
 360334,
 336251,
 890149,
 23135,
 91702,
 948014,
 585842,
 391068,
 43203,
 646694,
 970756,
 130236,
 771341,
 951217,
 517426,
 896281,
 963301,
 39505,
 149998,
 358938,
 719724,
 184704,
 235187,
 841374,
 562036,
 785523,
 579658,
 993727,
 728532,
 769416,
 46768

In [117]:
list_client_array[247752]

array(['13911384'], dtype='<U8')

In [118]:
# randonly choose clients 
list_client=list_client_array[mask].reshape((1,-1)).tolist()[0]
list_client

['15936535',
 '8455156',
 '6906848',
 '18506291',
 '9912772',
 '19733603',
 '8546167',
 '18456116',
 '16788427',
 '18948613',
 '20399627',
 '20239176',
 '15790518',
 '17101846',
 '24916733',
 '2583930',
 '6915723',
 '17391392',
 '17649088',
 '14736769',
 '13057579',
 '12776685',
 '20432364',
 '7774565',
 '12823135',
 '10639706',
 '10231376',
 '9260834',
 '18850678',
 '12168115',
 '17749343',
 '7204684',
 '14661702',
 '10401360',
 '17880211',
 '5525461',
 '19414660',
 '24960373',
 '18505254',
 '18013237',
 '25754168',
 '19077474',
 '11741016',
 '18311703',
 '10162134',
 '76433526',
 '11931790',
 '19094064',
 '17586159',
 '17936351',
 '17436283',
 '6590598',
 '12812645',
 '8918700',
 '22844310',
 '6893100',
 '7295035',
 '9039330',
 '10523771',
 '18506237',
 '8852351',
 '14642689',
 '12579537',
 '15681030',
 '7737186',
 '16117882',
 '17961094',
 '10091766',
 '17668206',
 '13058593',
 '24816709',
 '3224254',
 '11616717',
 '15963752',
 '13628518',
 '10822341',
 '7476740',
 '7738179',
 '1212

In [119]:
len(list_client)

20000

In [120]:
# convert the listo to a dataframe
client_df=pd.DataFrame(list_client)
client_df.columns=['clientcode']
client_df=client_df.sort_values(by='clientcode', ascending=True)
client_df

clientcode
6567    10000152
4072    10000422
6351    10002598
17789   10004910
3997    10005831
...          ...
16199    9996575
9567     9996888
2745     9997792
4104     9999153
9074     9999706

[20000 rows x 1 columns]

In [121]:
# describing the dataframe
client_df.describe()

clientcode
count       20000
unique      19815
top      17341506
freq            3

In [122]:
nr_client=len(list_client)

In [123]:
# dataframe filtered by randomly choosing clients
df_input=df_input[df_input['clientcode'].isin(list_client)]
df_input

clientcode hiercode nc
30        10000152  S525450  2
31        10000152  S022012  2
61        10000422  S523645  1
62        10000422  S521990  1
63        10000422  S500201  2
...            ...      ... ..
4933869    9996888  S000046  1
4933870    9996888  S009016  1
4934060    9997792  S528149  1
4934253    9999153  S501810  2
4934322    9999706  S530729  1

[95336 rows x 3 columns]

In [138]:
df_input.shape

(95336, 3)

In [125]:
# list of hiercode in df_input
list_hiercode=df_input['hiercode'].tolist()
len(list_hiercode)

95336

In [126]:
# converting list to set to eliminate duplicated and again converting to list
list_set_hiercode=list(set(df_input['hiercode'].tolist()) )
len(list_set_hiercode)

2478

In [127]:
# number of hiecode elements
nr_hiercode=len(list_set_hiercode)

In [128]:
# converting the list to a dataframe
dt_hiercode=pd.DataFrame(list_set_hiercode)

In [129]:
# adding the column name and ordering hiercode in ascending order
dt_hiercode.columns=['hiercode']
dt_hiercode=dt_hiercode.sort_values(by='hiercode', ascending=True)
dt_hiercode
idx_hiercode=pd.Series(dt_hiercode.index, index=dt_hiercode['hiercode'])
idx_hiercode

hiercode
S000003     109
S000011    2112
S000013     130
S000016    1314
S000029     551
           ... 
S531127    2084
S531129    2219
S531139    1986
S531147    1588
S531163    1775
Length: 2478, dtype: int64

In [130]:
# creating a matrix of 0's
s = (nr_client,nr_hiercode)
matrix=np.zeros(s)
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [131]:
matrix.shape

(20000, 2478)

In [132]:
# index for hiercode elements
dt_hiercode.index = pd.RangeIndex(len(dt_hiercode))
dt_hiercode.index

RangeIndex(start=0, stop=2478, step=1)

In [133]:
# build series where the index correspond to the hiercode element
idx_hiercode=pd.Series(dt_hiercode.index, index=dt_hiercode['hiercode'])
idx_hiercode


hiercode
S000003       0
S000011       1
S000013       2
S000016       3
S000029       4
           ... 
S531127    2473
S531129    2474
S531139    2475
S531147    2476
S531163    2477
Length: 2478, dtype: int64

In [134]:
# index for clients
client_df.index = pd.RangeIndex(len(client_df))
client_df.index
idx_client=pd.Series(client_df.index, index=client_df['clientcode'])
idx_client

clientcode
10000152        0
10000422        1
10002598        2
10004910        3
10005831        4
            ...  
9996575     19995
9996888     19996
9997792     19997
9999153     19998
9999706     19999
Length: 20000, dtype: int64

In [74]:
# Choosing an especific clientcode

In [75]:
clientcode='9999523'

In [76]:
# Retrieving the purchases of an specific client 
df_rut=df_input[df_input['clientcode'].isin([clientcode])]
df_rut=df_rut.sort_values(by='hiercode',ascending=True)
df_rut

Empty DataFrame
Columns: [clientcode, hiercode, nc]
Index: []

In [77]:
# retrieving the result to a list
list_df_result=df_rut['nc']
list_df_result

Series([], Name: nc, dtype: object)

In [78]:
df_rut['clientcode']

Series([], Name: clientcode, dtype: object)

In [79]:
idx_client_selected=idx_client[df_rut['clientcode']]
idx_client_selected

Series([], dtype: int64)

In [80]:
idx_hiercode_selected=list(idx_hiercode[df_rut['hiercode']])
idx_hiercode_selected

[]

In [81]:
idx_client_selected=list(idx_client[df_rut['clientcode']])
idx_client_selected

[]

In [82]:
matrix[idx_client_selected,idx_hiercode_selected]=list_df_result

In [83]:
matrix[idx_client_selected,idx_hiercode_selected]

array([], dtype=float64)

In [84]:
list_df_result

Series([], Name: nc, dtype: object)

In [85]:
## Alternativa 2: todo la muestra cargada de una vez

In [135]:
idx_client_selected=list(idx_client[df_input['clientcode']])
len(idx_client_selected)


96232

In [136]:
list_df_result=df_input['nc']
len(list_df_result)

95336

In [137]:
idx_hiercode_selected=list(idx_hiercode[df_input['hiercode']])
len(idx_hiercode_selected)

95336

In [97]:
matrix[idx_client_selected,idx_hiercode_selected]=list_df_result

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (98078,) (97423,) 

In [100]:
len(idx_client_selected)

98078

In [101]:
len(idx_hiercode_selected)

97423

In [91]:
matrix[idx_client_selected,idx_hiercode_selected]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (20000,) (2524,) 

In [40]:
len(list_df_result)

94208

In [106]:
list_client_array[mask]

array([['16086400'],
       ['17922391'],
       ['8702224'],
       ...,
       ['17766107'],
       ['4737232'],
       ['7042709']], dtype='<U8')

In [107]:
lit=list_client_array[mask].reshape((1,-1)).tolist()[0]


In [108]:
len(lit)

20000

In [163]:
client_df=pd.DataFrame(lit)
client_df.columns=['clientcode']
client_df=client_df.sort_values(by='clientcode', ascending=True)

In [164]:
client_df.describe()


clientcode
count       20000
unique      19820
top      15026440
freq            3

In [165]:
type(client_df['clientcode'][0])

str

In [166]:
client_df

clientcode
14746   10003567
18666   10004493
8297    10004665
11245   10006327
1323    10009379
...          ...
15135    9997674
4173     9998749
1908     9998856
18500    9999236
17130    9999638

[20000 rows x 1 columns]

In [109]:
nr_client=len(lit)

In [110]:
df_input=df_input[df_input['clientcode'].isin(lit)]

In [111]:
df_input.shape

(93747, 3)

In [112]:
list_hiercode=df_input['hiercode'].tolist()

In [113]:
len(list_hiercode)

93747

In [114]:
set_hiercode=set(df_input['hiercode'].tolist()) 
len(set_hiercode)

2502

In [115]:
set_hiercode

{'S529528',
 'S529707',
 'S527955',
 'S528351',
 'S530262',
 'S523685',
 'S528179',
 'S523673',
 'S524493',
 'S521232',
 'S530816',
 'S530380',
 'S000013',
 'S523853',
 'S527279',
 'S523847',
 'S529967',
 'S527291',
 'S523426',
 'S526402',
 'S502816',
 'S502220',
 'S528271',
 'S527077',
 'S530687',
 'S529503',
 'S530291',
 'S521979',
 'S527320',
 'S527697',
 'S527038',
 'S525108',
 'S529196',
 'S524378',
 'S526340',
 'S524323',
 'S528237',
 'S523535',
 'S502836',
 'S500343',
 'S529983',
 'S529824',
 'S500518',
 'S014016',
 'S525682',
 'S500744',
 'S527001',
 'S528164',
 'S530589',
 'S525008',
 'S528339',
 'S521990',
 'S527158',
 'S530152',
 'S530912',
 'S530264',
 'S529484',
 'S525469',
 'S530177',
 'S529438',
 'S001232',
 'S527054',
 'S524988',
 'S000077',
 'S521878',
 'S527222',
 'S524516',
 'S502686',
 'S004066',
 'S527690',
 'S524367',
 'S026001',
 'S525472',
 'S530884',
 'S529427',
 'S025004',
 'S530971',
 'S523874',
 'S502827',
 'S529371',
 'S529184',
 'S527086',
 'S525450',
 'S5

In [116]:
len(set_hiercode)

2502

In [117]:
nr_hiercode=len(set_hiercode)

In [118]:
dt_hiercode=pd.DataFrame(list(set_hiercode))

In [167]:
dt_hiercode.columns=['hiercode']
dt_hiercode=dt_hiercode.sort_values(by='hiercode', ascending=True)

In [80]:
dt_hiercode.to_excel (r'D:\projectos\recomendation\export_dataframe.xlsx', index = False, header=True)

In [131]:
df_input

clientcode hiercode nc
441       10003567  S526890  1
442       10003567  S527570  1
443       10003567  S523555  1
444       10003567  S530408  1
445       10003567  S011017  1
...            ...      ... ..
4934292    9999236  S525469  1
4934293    9999236  S528924  1
4934294    9999236  S050004  1
4934295    9999236  S501810  3
4934317    9999638  S000065  1

[93747 rows x 3 columns]

In [83]:
s = (nr_client,nr_hiercode)
matrix=np.zeros(s)

In [84]:
matrix.shape

(20000, 2558)

In [168]:
# indice de los hiercode
dt_hiercode.index = pd.RangeIndex(len(dt_hiercode.index))

In [169]:
dt_hiercode.index

RangeIndex(start=0, stop=2502, step=1)

In [170]:
idx_hiercode=pd.Series(dt_hiercode.index, index=dt_hiercode['hiercode'])
idx_hiercode

hiercode
S000003       0
S000011       1
S000013       2
S000016       3
S000029       4
           ... 
S531129    2497
S531139    2498
S531147    2499
S531155    2500
S531163    2501
Length: 2502, dtype: int64

In [171]:
idx_hiercode['S529528']

1992

In [172]:
# indice de los codeclient
client_df.index = pd.RangeIndex(len(client_df.index))


In [173]:
client_df.index

RangeIndex(start=0, stop=20000, step=1)

In [174]:
idx_client=pd.Series(client_df.index, index=client_df['clientcode'])
idx_client

clientcode
10003567        0
10004493        1
10004665        2
10006327        3
10009379        4
            ...  
9997674     19995
9998749     19996
9998856     19997
9999236     19998
9999638     19999
Length: 20000, dtype: int64

In [175]:
idx_client['9999638']

19999

In [176]:
type(idx_client)

pandas.core.series.Series

In [177]:
idx_client

clientcode
10003567        0
10004493        1
10004665        2
10006327        3
10009379        4
            ...  
9997674     19995
9998749     19996
9998856     19997
9999236     19998
9999638     19999
Length: 20000, dtype: int64

In [178]:
idx_hiercode

hiercode
S000003       0
S000011       1
S000013       2
S000016       3
S000029       4
           ... 
S531129    2497
S531139    2498
S531147    2499
S531155    2500
S531163    2501
Length: 2502, dtype: int64

In [179]:
idx_client['10003567']

0

In [180]:
idx_hiercode['S526890']

1235

In [220]:
df_rut=df_input[df_input['clientcode'].isin(['9999236'])]
df_rut=df_rut.sort_values(by='hiercode',ascending=True)

In [221]:
df_rut

clientcode hiercode  nc
4934270    9999236  S002098   3
4934276    9999236  S003065   2
4934281    9999236  S004065   1
4934294    9999236  S050004   1
4934282    9999236  S500618   1
4934295    9999236  S501810   3
4934265    9999236  S502874   1
4934258    9999236  S521890   3
4934262    9999236  S521891   1
4934288    9999236  S521926   3
4934267    9999236  S522093   1
4934257    9999236  S523749   2
4934268    9999236  S523890   1
4934278    9999236  S523897   1
4934271    9999236  S523898   1
4934263    9999236  S523972   1
4934285    9999236  S524474   5
4934277    9999236  S524482   1
4934256    9999236  S525434   1
4934292    9999236  S525469   1
4934283    9999236  S525592   1
4934286    9999236  S525953   1
4934284    9999236  S526867   1
4934255    9999236  S527034   1
4934266    9999236  S527206   2
4934272    9999236  S527261   2
4934260    9999236  S527975   1
4934293    9999236  S528924   1
4934280    9999236  S529462   1
4934290    9999236  S529832   1
4934259    9999236  S529944   2
4934273    9999236  S530745   4
4934274    9999236  S530835   1
4934269    9999236  S530845  12
4934291    9999236  S530850   1
4934264    9999236  S530874   2
4934289    9999236  S530889   1
4934261    9999236  S530907   2
4934287    9999236  S530942   1
4934279    9999236  S530943   1
4934275    9999236  S530957   2

In [222]:
list_df_result=df_rut['nc']

In [223]:
list_df_result

4934270     3
4934276     2
4934281     1
4934294     1
4934282     1
4934295     3
4934265     1
4934258     3
4934262     1
4934288     3
4934267     1
4934257     2
4934268     1
4934278     1
4934271     1
4934263     1
4934285     5
4934277     1
4934256     1
4934292     1
4934283     1
4934286     1
4934284     1
4934255     1
4934266     2
4934272     2
4934260     1
4934293     1
4934280     1
4934290     1
4934259     2
4934273     4
4934274     1
4934269    12
4934291     1
4934264     2
4934289     1
4934261     2
4934287     1
4934279     1
4934275     2
Name: nc, dtype: object

In [188]:
idx_client[df_rut['clientcode']]

clientcode
10003567    0
10003567    0
10003567    0
10003567    0
10003567    0
10003567    0
10003567    0
dtype: int64

In [224]:
idx_hiercode_selected=idx_hiercode[df_rut['hiercode']]

In [225]:
idx_hiercode_selected

hiercode
S002098      75
S003065      94
S004065     105
S050004     264
S500618     373
S501810     400
S502874     491
S521890     630
S521891     631
S521926     638
S522093     683
S523749     851
S523890     901
S523897     906
S523898     907
S523972     943
S524474    1041
S524482    1046
S525434    1132
S525469    1144
S525592    1150
S525953    1167
S526867    1224
S527034    1286
S527206    1413
S527261    1458
S527975    1624
S528924    1878
S529462    1974
S529832    2084
S529944    2139
S530745    2373
S530835    2398
S530845    2404
S530850    2407
S530874    2418
S530889    2423
S530907    2431
S530942    2448
S530943    2449
S530957    2457
dtype: int64

In [190]:
z = np.zeros([3, 3])
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [191]:
i = [[1, 1], [2, 0], [0, 2]]
i

[[1, 1], [2, 0], [0, 2]]

In [194]:
x, y = np.transpose(i)

In [195]:
x

array([1, 2, 0])

In [196]:
y

array([1, 0, 2])

In [197]:
print(type(i))

<class 'list'>


In [226]:
list_idx_hiercode_selected=list(idx_hiercode_selected)

In [232]:
idx_hiercode_selected['S530845']

2404

In [227]:
list_idx_hiercode_selected

[75,
 94,
 105,
 264,
 373,
 400,
 491,
 630,
 631,
 638,
 683,
 851,
 901,
 906,
 907,
 943,
 1041,
 1046,
 1132,
 1144,
 1150,
 1167,
 1224,
 1286,
 1413,
 1458,
 1624,
 1878,
 1974,
 2084,
 2139,
 2373,
 2398,
 2404,
 2407,
 2418,
 2423,
 2431,
 2448,
 2449,
 2457]

In [228]:
idx_client_selected=idx_client[df_rut['clientcode']]

In [229]:
list_idx_client_selected=list(idx_client_selected)
list_idx_client_selected

[19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998,
 19998]

In [230]:
matrix[list_idx_client_selected,list_idx_hiercode_selected]=list_df_result

In [231]:
matrix[list_idx_client_selected,list_idx_hiercode_selected]

array([ 3.,  2.,  1.,  1.,  1.,  3.,  1.,  3.,  1.,  3.,  1.,  2.,  1.,
        1.,  1.,  1.,  5.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,
        1.,  1.,  1.,  1.,  2.,  4.,  1., 12.,  1.,  2.,  1.,  2.,  1.,
        1.,  2.])

In [233]:
matrix[19998,2404]


12.0