In [169]:
#import mysql.connector
from sqlalchemy import create_engine
import pymysql
import numpy as np
import pandas as pd
from numpy.random import default_rng
from sklearn.metrics.pairwise import cosine_similarity

In [170]:
cnx = create_engine('mysql+pymysql://root:chilote64@localhost/analitica2')

In [171]:
qry="select	clientcode,hiercode,sum(nc) as nc from 	rp_client_preference_hst group by clientcode,hiercode"
df_input=pd.DataFrame(cnx.execute(qry).fetchall())
df_input.columns=['clientcode','hiercode','nc']

In [172]:
df_input.columns=['clientcode','hiercode','nc']

In [173]:
lst_client=list(set(df_input['clientcode'].tolist()))
len(lst_client)

1022972

In [174]:
def get_mask_list(lst_client,n_size):
    #convert list in a numpy array
    if len(lst_client)<n_size:
        return lst_client.tolist()
    else:
        list_client_array=np.array(lst_client).reshape((-1,1))
        rng = default_rng()
        random_array = rng.choice(len(lst_client), size=n_size, replace=False)
        mask=random_array.tolist()
        # randonly choose clients list_client
        return list_client_array[mask].reshape((1,-1)).tolist()[0]

In [175]:
def get_idx_client(list_client):
    client_df=pd.DataFrame(list_client)
    client_df.columns=['clientcode']
    client_df=client_df.sort_values(by='clientcode', ascending=True)
    # index for clients
    client_df.index = pd.RangeIndex(len(client_df))
    client_df.index
    # return idx_client
    idx_client=pd.Series(client_df.index, index=client_df['clientcode'])
    return idx_client
    

In [176]:
def get_df_filtered(list_client):
    # dataframe filtered by randomly choosing clients
    return df_input[df_input['clientcode'].isin(list_client)]
    

In [177]:
def get_idx_hiercode(df_new):
    list_hiercode=df_new['hiercode'].tolist()
    list_set_hiercode=list(set(list_hiercode) )
    dt_hiercode=pd.DataFrame(list_set_hiercode)
    dt_hiercode.columns=['hiercode']
    dt_hiercode=dt_hiercode.sort_values(by='hiercode', ascending=True)
    dt_hiercode.index = pd.RangeIndex(len(dt_hiercode))
    idx_hiercode=pd.Series(dt_hiercode.index, index=dt_hiercode['hiercode'])
    return idx_hiercode

In [178]:
def get_matrix(nr_client,nr_hiercode):
    s = (nr_client,nr_hiercode)
    matrix=np.zeros(s)
    return matrix

In [179]:
def update_matrix(df_new,idx_client,idx_hiercode):
    # retrieving the result to a list
    list_df_result=df_new['nc']
    idx_hiercode_selected=idx_hiercode[df_new['hiercode']]
    idx_client_selected=idx_client[df_new['clientcode']]
    matrix[idx_client_selected,idx_hiercode_selected]=list_df_result
    

In [180]:
def get_idx_client2(idx_client):
    iindex= pd.RangeIndex(len(list(idx_client)))
    idx_client2=pd.Series(idx_client.index, index=iindex)
    return idx_client2

In [181]:
def get_sim(i,n_size,cosine_matrix,idx_client2):
    mask=np.arange(i,n_size)
    x=cosine_matrix[i].reshape((-1, 1))
    x=x[mask]
    sim_col=x.astype(np.float)
    clientcode_rel=np.array(list(idx_client2[mask])).reshape((-1,1))
    clientcode=np.array([idx_client2[i]] * n_size).reshape((-1, 1))
    clientcode=clientcode[mask]
    matrix=np.concatenate([clientcode,clientcode_rel,sim_col], axis=1) 
    return [[a[0],a[1],a[2].astype(np.float)] for a in matrix if a[2].astype(np.float)>=0.5 and a[0]!=a[1]]

In [182]:
def get_sim_df(n_size,cosine_matrix,idx_client2):
    df=pd.DataFrame([],columns=['clientcode','clientcode_rel','sim_idx'])
    for i in range(n_size):
        lista=get_sim(i,n_size,cosine_matrix,idx_client2)
        matrix_df=pd.DataFrame(lista)
        if len(matrix_df)!=0:
                matrix_df.columns=['clientcode','clientcode_rel','sim_idx']
                df=pd.concat([df,matrix_df])
        else:
            pass
    return df
    

In [183]:
cycle=1
nr_cycles=87

In [184]:
n_size=12000

In [185]:
new_list=lst_client
other_list=[]

In [186]:
while cycle<=nr_cycles:
    # choose random list of clients
    client_list=get_mask_list(new_list,n_size)    
    # get index of clients
    idx_client=get_idx_client(client_list)
    # idx client inversa
    idx_client2=get_idx_client2(idx_client)
    # get df of clients tx
    df_new=get_df_filtered(client_list)
    # get index of hiercode
    idx_hiercode=get_idx_hiercode(df_new)
    # get matrix
    matrix=get_matrix(n_size,len(list(idx_hiercode)))
    #update matrix
    update_matrix(df_new,idx_client,idx_hiercode)
    cosine_matrix=cosine_similarity(matrix,matrix)
    df=get_sim_df(n_size,cosine_matrix,idx_client2)
    df.to_sql('rp_client_similarity', cnx, if_exists='append', chunksize=500, index=False)
    # calculate similarity
    #print(matrix.shape)
    #cosine_matrix=linear_kernel(matrix,matrix)
    #other list
    print(len(client_list))
    other_list=other_list+client_list
    # new_list
    new_list=set_diff = np.setdiff1d(lst_client, other_list)
    print(cycle)
    print(len(new_list))
    cycle=cycle+1

12000
1
1010972
12000
2
998972
12000
3
986972
12000
4
974972
12000
5
962972
12000
6
950972
12000
7
938972
12000
8
926972
12000
9
914972
12000
10
902972
12000
11
890972
12000
12
878972
12000
13
866972
12000
14
854972
12000
15
842972
12000
16
830972
12000
17
818972
12000
18
806972
12000
19
794972
12000
20
782972
12000
21
770972
12000
22
758972
12000
23
746972
12000
24
734972
12000
25
722972
12000
26
710972
12000
27
698972
12000
28
686972
12000
29
674972
12000
30
662972
12000
31
650972
12000
32
638972
12000
33
626972
12000
34
614972
12000
35
602972
12000
36
590972
12000
37
578972
12000
38
566972
12000
39
554972
12000
40
542972
12000
41
530972
12000
42
518972
12000
43
506972
12000
44
494972
12000
45
482972
12000
46
470972
12000
47
458972
12000
48
446972
12000
49
434972
12000
50
422972
12000
51
410972
12000
52
398972
12000
53
386972
12000
54
374972
12000
55
362972
12000
56
350972
12000
57
338972
12000
58
326972
12000
59
314972
12000
60
302972
12000
61
290972
12000
62
278972
12000
63
266972


KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Int64Index([ 2972,  2973,  2974,  2975,  2976,\n            ...\n            11995, 11996, 11997, 11998, 11999],\n           dtype='int64', length=9028). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

In [187]:
cosine_matrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [79]:
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [80]:
df_new

clientcode hiercode nc
542       10003789  S526407  1
543       10003789  S529402  1
601       10004493  S523888  1
1863      10010809  S528026  1
1864      10010809  S521874  1
...            ...      ... ..
4932284    9992313  S523872  1
4932285    9992313  S523873  1
4932286    9992313  S526007  1
4932973    9993768  S525050  1
4933165    9994260  S522028  2

[58088 rows x 3 columns]

12000

In [101]:
idx_client=get_idx_client(client_list)
idx_client

clientcode
10001269        0
10005906        1
10007225        2
10011504        3
10011623        4
            ...  
9992812     11995
9992818     11996
9996020     11997
9996381     11998
9997087     11999
Length: 12000, dtype: int64

In [102]:
idx_client2=get_idx_client2(idx_client)
idx_client2

0        10001269
1        10005906
2        10007225
3        10011504
4        10011623
           ...   
11995     9992812
11996     9992818
11997     9996020
11998     9996381
11999     9997087
Name: clientcode, Length: 12000, dtype: object

In [103]:
df_new=get_df_filtered(client_list)
df_new

clientcode hiercode nc
121       10001269  S529519  1
797       10005906  S527248  1
798       10005906  S009004  1
799       10005906  S527244  1
800       10005906  S527266  1
...            ...      ... ..
4933798    9996381  S522484  1
4933799    9996381  S522481  1
4933800    9996381  S529701  1
4933801    9996381  S529733  1
4933896    9997087  S529822  1

[58311 rows x 3 columns]

In [104]:
idx_hiercode=get_idx_hiercode(df_new)
idx_hiercode

hiercode
S000003       0
S000011       1
S000013       2
S000016       3
S000029       4
           ... 
S531090    2344
S531129    2345
S531139    2346
S531147    2347
S531163    2348
Length: 2349, dtype: int64

In [105]:
matrix=get_matrix(n_size,len(list(idx_hiercode)))
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [106]:
matrix.shape

(12000, 2349)

In [107]:
update_matrix(df_new,idx_client,idx_hiercode)
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [108]:
idx_client['9996381']

11998

In [114]:
idx_hiercode['S522484']
idx_hiercode['S522481']
idx_hiercode['S529701']

1903

In [115]:
matrix[11998,1903]

1.0

In [111]:
matrix[11998].tolist()

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [117]:
cosine_matrix=cosine_similarity(matrix,matrix)
cosine_matrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [118]:
cosine_matrix[0].tolist()

[1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [119]:
df=pd.DataFrame(cosine_matrix[0].tolist())
df.to_excel (r'D:\projectos\recomendation\export_dataframe.xlsx', index = False, header=True)

In [137]:
mask=np.arange(2500,n_size)
mask

array([ 2500,  2501,  2502, ..., 11997, 11998, 11999])

In [138]:
x=cosine_matrix[2500].reshape((-1, 1))

In [139]:
x=x[mask]
sim_col=x.astype(np.float)
sim_col

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [140]:
clientcode_rel=np.array(list(idx_client2[mask])).reshape((-1,1))
clientcode_rel


array([['13440186'],
       ['13440612'],
       ['13441651'],
       ...,
       ['9996020'],
       ['9996381'],
       ['9997087']], dtype='<U8')

In [141]:
clientcode=np.array([idx_client2[2500]] * n_size).reshape((-1, 1))
clientcode=clientcode[mask]
clientcode

array([['13440186'],
       ['13440186'],
       ['13440186'],
       ...,
       ['13440186'],
       ['13440186'],
       ['13440186']], dtype='<U8')

In [142]:
matrix=np.concatenate([clientcode,clientcode_rel,sim_col], axis=1) 
matrix

array([['13440186', '13440186', '1.0'],
       ['13440186', '13440612', '0.0'],
       ['13440186', '13441651', '0.0'],
       ...,
       ['13440186', '9996020', '0.0'],
       ['13440186', '9996381', '0.0'],
       ['13440186', '9997087', '0.0']], dtype='<U32')

In [143]:
[[a[0],a[1],a[2].astype(np.float)] for a in matrix if a[2].astype(np.float)>=0.5 and a[0]!=a[1]]

[['13440186', '14112252', 1.0],
 ['13440186', '14523479', 0.5773502691896258],
 ['13440186', '14527228', 0.7071067811865475],
 ['13440186', '16007849', 1.0],
 ['13440186', '16188240', 0.5773502691896258],
 ['13440186', '18246814', 1.0],
 ['13440186', '19149802', 0.7071067811865475],
 ['13440186', '20046353', 0.7071067811865475],
 ['13440186', '23812823', 0.7071067811865475],
 ['13440186', '23824231', 0.5773502691896258],
 ['13440186', '25111542', 0.5773502691896258],
 ['13440186', '3731378', 0.5773502691896258],
 ['13440186', '4406195', 0.5345224838248488],
 ['13440186', '5325829', 0.7071067811865475],
 ['13440186', '5798654', 1.0],
 ['13440186', '5820041', 1.0],
 ['13440186', '6362162', 0.5],
 ['13440186', '6553149', 0.7071067811865475],
 ['13440186', '7797967', 0.6666666666666666],
 ['13440186', '7830138', 0.5773502691896258],
 ['13440186', '9046023', 0.7717436331412897]]

In [147]:
df=get_sim_df(n_size,cosine_matrix,idx_client2)

In [149]:
df.shape

(598892, 3)