In [1]:
#import mysql.connector
from sqlalchemy import create_engine
import pymysql
import numpy as np
import pandas as pd
from numpy.random import default_rng
from sklearn.metrics.pairwise import linear_kernel

In [2]:
#cnx = sqlalchemy.create_engine('mysql+pymysql://root:chilote64@localhost/analitica2')
cnx = create_engine('mysql+pymysql://root:chilote64@localhost/analitica2')

In [3]:
qry="select	clientcode,hiercode,sum(nc) as nc from 	rp_client_preference_hst group by clientcode,hiercode"
df_input=pd.DataFrame(cnx.execute(qry).fetchall())
df_input.columns=['clientcode','hiercode','nc']

In [4]:
df_input.columns=['clientcode','hiercode','nc']

In [5]:
# entire dataframe
df_input

clientcode hiercode nc
0               10  S523920  1
1               10  S524478  1
2          1000000  S527972  1
3          1000000  S527224  1
4          1000000  S522143  1
...            ...      ... ..
4935154   99999999  S528290  1
4935155   99999999  S500668  3
4935156   99999999  S527079  2
4935157   99999999  S529192  1
4935158   99999999  S530935  1

[4935159 rows x 3 columns]

In [6]:
df_input.shape

(4935159, 3)

In [7]:
lst_client=list(set(df_input['clientcode'].tolist()))
len(lst_client)

1022972

In [8]:
list_client_array=np.array(lst_client).reshape((-1,1))

In [9]:
list_client_array

array([['11721868'],
       ['9817339'],
       ['15671487'],
       ...,
       ['16386027'],
       ['11931039'],
       ['19099612']], dtype='<U8')

In [10]:
# Number of clients to choose randomly
n=22000

In [11]:
rng = default_rng()
random_array = rng.choice(len(lst_client), size=n, replace=False)

In [12]:
random_array.shape

(22000,)

In [13]:
# convering the index array to a list
mask=random_array.tolist()
mask

[772709,
 887485,
 457101,
 162351,
 882386,
 52460,
 881227,
 400269,
 289903,
 969372,
 55053,
 603600,
 789236,
 128108,
 835061,
 1022729,
 470607,
 494936,
 211919,
 464737,
 167786,
 749835,
 383858,
 369834,
 810650,
 649867,
 798384,
 826294,
 149740,
 505488,
 154963,
 924427,
 690375,
 485533,
 899690,
 423446,
 244986,
 14211,
 330588,
 20084,
 739032,
 699052,
 874037,
 119805,
 235316,
 19760,
 741014,
 393048,
 652756,
 994826,
 543616,
 865281,
 64255,
 5931,
 729149,
 638037,
 483515,
 180479,
 193678,
 905469,
 414425,
 160326,
 188848,
 490365,
 534824,
 833682,
 285477,
 374713,
 50670,
 522111,
 613904,
 574179,
 542965,
 461561,
 645031,
 797742,
 777025,
 592874,
 482126,
 63353,
 5366,
 975200,
 6257,
 852574,
 943752,
 430557,
 1014295,
 628245,
 997082,
 715497,
 838218,
 548997,
 484392,
 212936,
 156144,
 358314,
 759321,
 401622,
 601909,
 366450,
 334709,
 369641,
 689601,
 770476,
 476093,
 56521,
 60429,
 365224,
 338644,
 105822,
 50956,
 646701,
 269505

In [14]:
len(mask)

22000

In [15]:
# randonly choose clients 
list_client=list_client_array[mask].reshape((1,-1)).tolist()[0]
len(list_client)

22000

In [16]:
# convert the list to a dataframe
client_df=pd.DataFrame(list_client)
client_df.columns=['clientcode']
client_df=client_df.sort_values(by='clientcode', ascending=True)
client_df.shape

(22000, 1)

In [17]:
# describing the dataframe
client_df.describe()

clientcode
count       22000
unique      22000
top      12019091
freq            1

In [18]:
# index for clients
client_df.index = pd.RangeIndex(len(client_df))
client_df.index
idx_client=pd.Series(client_df.index, index=client_df['clientcode'])
idx_client.shape

(22000,)

In [19]:
idx_client

clientcode
10000479        0
10002293        1
10003028        2
10004170        3
10004493        4
            ...  
9993890     21995
9994617     21996
9994757     21997
9994864     21998
9997341     21999
Length: 22000, dtype: int64

In [20]:
nr_client=len(list_client)
nr_client

22000

In [21]:
# dataframe filtered by randomly choosing clients
df_input=df_input[df_input['clientcode'].isin(list_client)]
df_input

clientcode hiercode nc
74        10000479  S018006  1
75        10000479  S025008  1
200       10002293  S529834  1
201       10002293  S529402  1
202       10002293  S002013  1
...            ...      ... ..
4933957    9997341  S039004  2
4933958    9997341  S530125  1
4933959    9997341  S043004  2
4933960    9997341  S530447  1
4933961    9997341  S530476  3

[103413 rows x 3 columns]

In [22]:
# list of hiercode in df_input
list_hiercode=df_input['hiercode'].tolist()
len(list_hiercode)

103413

In [23]:
# converting list to set to eliminate duplicated and again converting to list
list_set_hiercode=list(set(list_hiercode) )
len(list_set_hiercode)

2494

In [24]:
# converting the list to a dataframe
dt_hiercode=pd.DataFrame(list_set_hiercode)
dt_hiercode.shape

(2494, 1)

In [25]:
# adding the column name and ordering hiercode in ascending order
dt_hiercode.columns=['hiercode']
dt_hiercode=dt_hiercode.sort_values(by='hiercode', ascending=True)
dt_hiercode


hiercode
2016  S000002
2067  S000003
250   S000011
1432  S000013
1255  S000016
...       ...
352   S531129
1238  S531139
757   S531147
2281  S531155
2372  S531163

[2494 rows x 1 columns]

In [26]:
# index for hiercode elements
dt_hiercode.index = pd.RangeIndex(len(dt_hiercode))
dt_hiercode.index

RangeIndex(start=0, stop=2494, step=1)

In [27]:
idx_hiercode=pd.Series(dt_hiercode.index, index=dt_hiercode['hiercode'])
idx_hiercode.shape

(2494,)

In [28]:
# number of hiecode elements
nr_hiercode=len(list_set_hiercode)

In [29]:
# creating a matrix of 0's
s = (nr_client,nr_hiercode)
matrix=np.zeros(s)
matrix.shape

(22000, 2494)

In [30]:
# retrieving the result to a list
list_df_result=df_input['nc']
len(list_df_result)

103413

In [31]:
# hiercode index of tx
idx_hiercode_selected=idx_hiercode[df_input['hiercode']]
idx_hiercode_selected.shape

(103413,)

In [32]:
# client index of tx
idx_client_selected=idx_client[df_input['clientcode']]
idx_client_selected.shape

(103413,)

In [33]:
matrix[idx_client_selected,idx_hiercode_selected]=list_df_result

In [34]:
cosine_matrix=linear_kernel(matrix,matrix)

In [36]:
cosine_matrix.shape

(22000, 22000)

In [37]:
matrix.shape

(22000, 2494)

In [54]:
nr_cycles=47

In [38]:
matrix.shape

(22000, 2494)

In [55]:
len(lst_client)

1022972

In [56]:
# sustraction of client from list
new_list=set_diff = np.setdiff1d(lst_client, list_client)

In [57]:
# new list
len(new_list)

1000972

In [63]:
#new mask

rng = default_rng()
random_array = rng.choice(len(new_list), size=n, replace=False)

In [64]:
# convering the index array to a list
mask=random_array.tolist()
mask

[42449,
 47651,
 581103,
 322051,
 429773,
 896182,
 147343,
 528213,
 461262,
 253731,
 575617,
 323954,
 934700,
 95745,
 782515,
 135162,
 152751,
 46538,
 460081,
 617653,
 131292,
 505642,
 430466,
 830165,
 275857,
 896160,
 282808,
 762831,
 725386,
 837956,
 794656,
 71232,
 862189,
 267883,
 689266,
 504689,
 769177,
 384241,
 33807,
 155038,
 608069,
 982535,
 111204,
 668808,
 167156,
 614232,
 42341,
 359303,
 880695,
 449733,
 773285,
 159044,
 225627,
 796774,
 115815,
 324059,
 735161,
 321063,
 745300,
 77520,
 951272,
 69214,
 424589,
 380019,
 530517,
 980514,
 949724,
 308675,
 796021,
 421547,
 740001,
 205871,
 562518,
 209871,
 934720,
 768515,
 474485,
 376522,
 309159,
 817718,
 490660,
 273948,
 351248,
 803791,
 33559,
 876622,
 971457,
 20276,
 667366,
 153571,
 791370,
 615411,
 942586,
 553778,
 932841,
 28388,
 800518,
 549563,
 888608,
 403059,
 595119,
 785125,
 403576,
 273487,
 991093,
 792547,
 764836,
 935841,
 87279,
 429083,
 279864,
 200985,
 9783

In [65]:
len(mask)

22000

In [66]:
list_client_array=np.array(new_list).reshape((-1,1))

In [67]:
# randonly choose clients 
list_client=list_client_array[mask].reshape((1,-1)).tolist()[0]
len(list_client)

22000

In [68]:
# convert the list to a dataframe
client_df=pd.DataFrame(list_client)
client_df.columns=['clientcode']
client_df=client_df.sort_values(by='clientcode', ascending=True)
client_df.shape

(22000, 1)

In [69]:
# index for clients
client_df.index = pd.RangeIndex(len(client_df))
client_df.index
idx_client=pd.Series(client_df.index, index=client_df['clientcode'])
idx_client.shape

(22000,)

In [70]:
nr_client=len(list_client)
nr_client

22000

In [71]:
# dataframe filtered by randomly choosing clients
df_input_new=df_input[df_input['clientcode'].isin(list_client)]
df_input_new

clientcode hiercode nc
121       10001269  S529519  1
546       10003845  S527432  1
547       10003845  S529811  1
1278      10008556  S500344  3
1279      10008556  S502736  3
...            ...      ... ..
4933870    9996888  S009016  1
4934071    9997820  S529762  1
4934072    9997820  S530890  1
4934073    9997820  S007040  1
4934336    9999850  S523843  1

[105862 rows x 3 columns]

In [72]:
# list of hiercode in df_input
list_hiercode=df_input_new['hiercode'].tolist()
len(list_hiercode)

105862

In [73]:
# converting list to set to eliminate duplicated and again converting to list
list_set_hiercode=list(set(list_hiercode) )
len(list_set_hiercode)

2501

In [74]:
# converting the list to a dataframe
dt_hiercode=pd.DataFrame(list_set_hiercode)
dt_hiercode.shape

(2501, 1)

In [75]:
# adding the column name and ordering hiercode in ascending order
dt_hiercode.columns=['hiercode']
dt_hiercode=dt_hiercode.sort_values(by='hiercode', ascending=True)
dt_hiercode

hiercode
1804  S000003
214   S000011
1901  S000013
1192  S000016
1849  S000029
...       ...
1748  S531090
1409  S531129
1489  S531139
153   S531147
1584  S531163

[2501 rows x 1 columns]

In [76]:
# index for hiercode elements
dt_hiercode.index = pd.RangeIndex(len(dt_hiercode))
dt_hiercode.index

RangeIndex(start=0, stop=2501, step=1)

In [84]:
idx_hiercode=pd.Series(dt_hiercode.index, index=dt_hiercode['hiercode'])
idx_hiercode.shape

(2501,)

In [85]:
# number of hiecode elements
nr_hiercode=len(list_set_hiercode)

In [86]:
# creating a matrix of 0's
s = (nr_client,nr_hiercode)
matrix=np.zeros(s)
matrix.shape

(22000, 2501)

In [87]:
# retrieving the result to a list
list_df_result=df_input_new['nc']
len(list_df_result)

105862

In [88]:
# hiercode index of tx
idx_hiercode_selected=idx_hiercode[df_input_new['hiercode']]
idx_hiercode_selected.shape

(105862,)

In [89]:
# client index of tx
idx_client_selected=idx_client[df_input_new['clientcode']]
idx_client_selected.shape

(105862,)

In [90]:
matrix[idx_client_selected,idx_hiercode_selected]=list_df_result

In [56]:
cosine_matrix=linear_kernel(matrix,matrix)

In [39]:
cosine_matrix

array([[ 2.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  4.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0., 30., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  8.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0., 55.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0., 28.]])

In [ ]:
def get_sim_matrix(i,n,hiercode,cosine_similarities_matrix,idx_vector):
        print((" iteracion N° {}").format(i))
        # vector similarities en i
        # columna con similarities
        mask=np.arange(i,n)
        x=cosine_similarities_matrix[i].reshape((-1, 1))
        x=x[mask]
        sim_col=x.astype(np.float)
        # calcula indices
        #idx_vector=get_idx(dfiltered)
        idx_vector_array=np.array(list(idx_vector[mask])).reshape((-1,1))
        # prodcode
        prodcode=idx_vector[i]
        # id
       #idd=np.arange(idinicio,idinicio+n).reshape((-1,1))
        # antecedent
        antecedent=np.array([prodcode] * n).reshape((-1, 1))
        antecedent=antecedent[mask]
        hiercode=np.array([hiercode] * n).reshape((-1, 1))
        hiercode=hiercode[mask]
        matrix=np.concatenate([hiercode,antecedent,idx_vector_array,sim_col], axis=1) 
        return [[a[0],a[1],a[2],a[3].astype(np.float)] for a in matrix if a[3].astype(np.float)>=0.5 and a[1]!=a[2]]

In [63]:
i=1

In [64]:
n=cosine_matrix.shape[0]
n

22000

In [65]:
mask=np.arange(i,n)

In [66]:
mask

array([    1,     2,     3, ..., 21997, 21998, 21999])

In [67]:
x=cosine_matrix[i].reshape((-1, 1))

In [68]:
x

array([[0.],
       [4.],
       [0.],
       ...,
       [0.],
       [1.],
       [0.]])

In [59]:
x=x[mask]

In [60]:
x

array([[2.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [61]:
sim_col=x.astype(np.float)

In [62]:
sim_col[200]

array([0.])